name: PR review
on:
  pull_request:
    branches: [ main ]

jobs:
  prReview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm install
      - name: Run script
        env:
          TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          node .github/actions-scripts/app.js