name: PR review

on:
  pull_request_target:
    branches: 
      - main

jobs:
  pr-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: main
          path: master
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          path: branch
      - name: kong pr review
        id: kong-pr-review
        uses: 321pranay-org/kong-pr-review@v1
        env:
          TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.number }} 